### ISSUE TITLE
Broken link on readme.md

### ISSUE THREAD

**Issue by dahovey** [microsoft/winget-cli-restsource#104]
### Brief description of your issue

At main readme.md, under subheading "Automatically create a rest source" the link to powershell `New-WinGetSource` is broken.

https://github.com/microsoft/winget-cli-restsource#automatically-create-a-rest-source

**Comment by RDMacLachlan** [comment]
Thank you @dahovey for the feedback. The following PR has been submitted and is awaiting approval to correct the links.

https://github.com/microsoft/winget-cli-restsource/pull/106
