### ISSUE TITLE
Support installing .zip files

### ISSUE THREAD

**Issue by RDMacLachlan** [microsoft/winget-cli-restsource#117]
### Description of the new feature / enhancement

[Placeholder]

Related to:
* https://github.com/microsoft/winget-cli/issues/140

### Proposed technical implementation details

> Note:
> This is pending a specification documentation.

**Comment by eabase** [comment]
I think the future in **now**... 💯 

From my own GitHub experience, anything labelled or out into a "future" project, will never happen! 👎

**Comment by denelon** [comment]
WinGet 1.4 support .zip as an installer type with either a single nested instaler, or one or more portable packages.
