### ISSUE TITLE
Missing support for Store content

### ISSUE THREAD

**Issue by jamespik** [microsoft/winget-cli-restsource#17]
Arch: x86
  InstallerType: MSStore
  ProductId: 9N0CTDPL6ZC3
  PackageFamilyName: 10011IRXON.atBlue_96p6fcx5kk12j

A rest source needs to be able to return a store installer type with a product id.

**Comment by RDMacLachlan** [comment]
Administrators are now able to host their own REST source, and include MSStore type apps in their REST source.
