### ISSUE TITLE
New-WinGetSource documentation references an -Index parameter that doesn't exist

### ISSUE THREAD

**Issue by ghost** [microsoft/winget-cli-restsource#174]
There are several places where an -Index parameter for New-WinGetSource is referenced, but it does not exist (nor does it look like it's [ever existed](https://github.com/microsoft/winget-cli-restsource/blob/747b4336ae455e4cc5319f8e4f7c2c76cabe0a41/Tools/PowershellModule/src/Library/New-WinGetSource.ps1)).

https://github.com/microsoft/winget-cli-restsource/blob/d7df69f4d84daeb1db5ed8ef5a3af656f36e5d07/Tools/PowershellModule/src/Library/New-WinGetSource.ps1#L21

https://github.com/microsoft/winget-cli-restsource/blob/d7df69f4d84daeb1db5ed8ef5a3af656f36e5d07/Tools/PowershellModule/doc/PowerShell/New-WinGetSource.md?plain=1#L65

https://github.com/microsoft/winget-cli-restsource/blob/d7df69f4d84daeb1db5ed8ef5a3af656f36e5d07/README.md?plain=1#L60

(Also worth noting the README.md says this parameter is "Required" = "Yes", while New-WinGetSource.md says it's optional.)

**Comment by RDMacLachlan** [comment]
Thank you @ameltzerMSFT .
