### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by trhumphries** [microsoft/winget-cli-restsource#187]
### Brief description of your issue

I don't see how anyone has been able to use this project. It refers to old MS internal code nuget packages, doesn't include everything Bond need to include to build the project.

### Steps to reproduce

Check it out and try to build it

### Expected behavior

If should build

### Actual behavior

Completely broken

### Environment

```shell
Windows
```

**Comment by RDMacLachlan** [comment]
We have updated the PowerShell scripts used to stand-up a new REST source on Azure.
