### ISSUE TITLE
Parameter missing in Automate the creation of a Windows Package Manager REST source

### ISSUE THREAD

**Issue by rahulkj30** [microsoft/winget-cli-restsource#209]
### Brief description of your issue

while executing below command **New-WinGetSource -Name "contosorestsource" -ResourceGroup "WinGet" -Region "westus" -ImplementationPerformance "Demo" -ShowConnectionInstructions** it is requesting for additionalparameters which is missing in document

additional parameter
manifestCacheEndpoint: 
monitoringTenant: 
monitoringRole: 
monitoringMetricsAccount:

**Comment by RDMacLachlan** [comment]
This has been resolved 👍
