### ISSUE TITLE
New-WinGetSource cmdlet doesn't exist

### ISSUE THREAD

**Issue by thilojaeggi** [microsoft/winget-cli-restsource#210]
### Brief description of your issue

The cmdlet described thoroughly here: https://github.com/microsoft/winget-cli-restsource/blob/main/Tools/PowershellModule/doc/PowerShell/New-WinGetSource.md, doesn't seem to exist.

**Comment by RDMacLachlan** [comment]
The "New-WinGetSource" is part of a release artifact of this project. There were issues raised with the scripts functionality that we are working to resolve.
