### ISSUE TITLE
Max Installer Nodes 1024

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli-restsource#31]
# Description of the new feature/enhancement

The maximum number of installer nodes should be increased. ~[Firefox has 231](https://github.com/microsoft/winget-pkgs/discussions/13266#discussioncomment-748775).~ [Firefox has 291](https://github.com/microsoft/winget-pkgs/discussions/13266#discussioncomment-748844).

# Proposed technical implementation details (optional)

Increase the maximum number of installer nodes to ~256~ ~512~ 1024.
This needs to be implemented in the:
* Client validation - https://github.com/microsoft/winget-cli/issues/967
* Manifest schema - https://github.com/microsoft/winget-cli/issues/967
* PR validation - https://github.com/microsoft/winget-pkgs/issues/13373
* REST schema

**Comment by denelon** [comment]
It looks like we still need this work item to be completed to limit the number of installer nodes to 1024 in the REST API.

**Comment by yao-msft** [comment]
The rest implementation does not limit the number of installer nodes(and client parsing also supports that). In order not to do a potential breaking change, we did not change the rest implementation.
