### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli-restsource#34]
We should have a high level description of the project in the README including some steps for deploying the project.

**Comment by jedieaston** [comment]
I've been trying for three days and I can't get this thing to run, I think it needs some environment variables or something. I can't get it to run locally or on Azure. 

If someone could give me some guidance on where to put the settings for Cosmos DB, storage, etc. I can flesh it out into a doc. The WinGet.RestSource.Infrastructure project just looks like some kind of template with no information on what I need to spin up or where, although maybe that's just because I don't understand ARM templates :D

**Comment by denelon** [comment]
@jedieaston

@zacharp and I have been talking about this over the last couple of days. More guidance will be coming as soon as his current feature work is wrapped up. We've been talking about a "minimum" configuration to just stand-up a lightweight developer type environment as opposed to an enterprise grade configuration. The database choice can also be abstracted by an interface so other "database" technologies could be used.

**Comment by denelon** [comment]
@RDMacLachlan is about to make a PR with a PowerShell script and instructions for deploying the project. We still need to build a release pipeline so the .zip files can be published in a release. Optionally someone from the community might want to look at the PowerShell script and add some extra magic to download the latest released artifacts to make deploying even more simple.

**Comment by jedieaston** [comment]
This looks good. Any chance of getting instructions on local development? If not this will help anyway, but those Azure for Students credits only go so far :D

**Comment by RDMacLachlan** [comment]
Hi @jedieaston,

As part of this PR, we did include documentation on how to manually create each object in Azure. While the script and manual creation will consume Azure credits, the manual guidance does outline the individual objects required to host a Windows Package Manager private repository.

@denelon - Do you think we could make use of the Azure Cosmos DB Emulator, and a webserver to host the private repository on-premises? Can we make use of a SQL Database?

**Creating a Windows Package Manager private repository guidance:**
https://github.com/microsoft/winget-cli-restsource/blob/da4168a61fdd0b35900831bd22338249ae886bf4/doc/new-private-repository-azure.md

**Comment by denelon** [comment]
@RDMacLachlan I believe there is an interface for the storage. One could build a SQL interface. I'm not sure about the Cosmos DB Emulator scenario. I am not aware of anything preventing that technology stack.
