### ISSUE TITLE
Build Pipeline for Releases

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli-restsource#60]
# Build Pipeline for Releases

As a part of #34 I mentioned having the release artifacts published so the deploy process can be made even more simple. It has a dependency on the .zip file produced when building the project.

# Proposed technical implementation details (optional)

Create a build pipeline and publish a release 😊.

**Comment by RDMacLachlan** [comment]
The script assumes that the location of the *.zip is in the "Src/WinGet.RestSource.Infrastructure" and that the file name is "CompiledFunctions.zip".

These values are set at the parameter inputs, and can be overwritten by the user. However I'd like to make this more friendly to just generic usage and update the expected paths and file names.
